<template>
  <div class="column" ref="div-column">
    
    <div class="row-auto">
      <q-search v-model="searchText" placeholder="Rechercher un Graaly" />
    </div>
    
    <div class="row" ref="map" v-if="geolocationIsSupported">
      
      <gmap-map
        :center="mapCenter"
        :zoom="11"
        map-type-id="roadmap"
        class="map"
        ref="map"
        :options="{disableDefaultUI:true}"
        @center_changed="updateCenter($event)"
      >
        <gmap-marker v-for="(graaly, index) in graalyList" :key="graaly.id" :position="graaly.position" :icon="graalyMarker"
          @click="onGraalyClick(graaly, index)" />
        
        <gmap-info-window :options="infoWindow.options" :position="infoWindow.position" :opened="infoWindow.isOpen" @closeclick="infoWindow.isOpen=false">
          <div class="infoWindow">
            <h1> {{ currentGraaly ? currentGraaly.title : '' }} </h1>
            <p>[[Difficulté]]</p>
            <p><button @click="$router.push('/graaly/play/' + (currentGraaly ? currentGraaly.id : ''))">Enquêter</button></p>
          </div>
        </gmap-info-window>
        
      </gmap-map>

    </div>
    
    <div class="row-auto">
      <q-btn icon="create" @click="$router.push('/graaly/create')">Créer un Graaly</q-btn>
    </div>
    
  </div>
</template>

<script>
export default {
  data () {
    return {
      title: 'Carte',
      mapCenter: { lat: 0, lng: 0 },
      infoWindow: {
        content: '',
        position: { lat: 0, lng: 0 },
        isOpen: false,
        options: { pixelOffset: { width: 0, height: -35 } }
      },
      currentGraalyIndex: null,
      currentGraaly: null,
      // for smooth 'panTo()' transition between marker clicks
      pan: {
        path: [],
        queue: [],
        steps: 20,
        duration: 700, // in milliseconds
        timeout: null // object generated by 'setTimeout()'
      },
      geolocationIsSupported: navigator.geolocation,
      searchText: '',
      graalyList: [
        { id: 1, title: 'Le Clos des Chartreux, Tullins', position: { lat: 45.3, lng: 5.5 } },
        { id: 2, title: 'Le Parc de la Grille, Moirans', position: { lat: 45.33, lng: 5.56 } },
        { id: 3, title: 'Les cadrans solaires, Vourey', position: { lat: 45.32, lng: 5.52 } },
        { id: 4, title: 'Les méandres de l\'Isère, Gières', position: { lat: 45.2, lng: 5.8 } },
        { id: 5, title: 'Découvrir Lumbin', position: { lat: 45.3, lng: 5.9 } },
        { id: 6, title: 'Jeu de piste à Brigoud', position: { lat: 45.26, lng: 5.9 } },
        { id: 7, title: 'Quelque chose se passe à Bernin', position: { lat: 45.269, lng: 5.867 } },
        { id: 8, title: 'Avenue Jean Jaurès, Grenoble', position: { lat: 45.19, lng: 5.72 } }
      ],
      graalyMarker: {
        url: 'statics/icons/game/graaly.png',
        size: {width: 45, height: 45, f: 'px', b: 'px'},
        scaledSize: {width: 30, height: 30, f: 'px', b: 'px'},
        origin: {x: 0, y: 0},
        anchor: {x: 15, y: 15}
      }
    }
  },
  mounted() {
    // dispatch specific title for other app components
    this.$store.dispatch('setTitle', this.$data.title);
    
    if (this.$data.geolocationIsSupported) {
      navigator.geolocation.getCurrentPosition((position) => {
        this.$data.mapCenter = {lat: position.coords.latitude, lng: position.coords.longitude}
      });
    }
  },
  methods: {
    onGraalyClick(graaly, idx) {
      let infoWindow = this.infoWindow
      this.infoWindow.position = graaly.position
      
      //check if its the same marker that was selected if yes toggle
      if (this.currentGraalyIndex === idx) {
        infoWindow.isOpen = !infoWindow.isOpen
      }
      //if different marker, set infowindow to open and reset current marker index
      else {
        infoWindow.isOpen = true
        this.currentGraalyIndex = idx
        this.currentGraaly = this.graalyList[idx]
        // center map on last clicked Graaly
        this.panTo(graaly.position)
      }
    },
    
    // from https://stackoverflow.com/a/33339155/488666
    panTo (position) {
      let panPath = this.pan.path
      let panQueue = this.pan.queue
      let panSteps = this.pan.steps
      if (panPath.length > 0) {
        // We are already panning...queue this up for next move
        panQueue.push(position)
      } else {
        // easeIn animation computation: see https://stackoverflow.com/a/11808697/488666
        panPath.push("LAZY SYNCRONIZED LOCK")  // make length non-zero - 'release' this before calling setTimeout
        var curLat = this.mapCenter.lat
        var curLng = this.mapCenter.lng
        var dLat = (position.lat - curLat)
        var dLng = (position.lng - curLng)
        
        for (var i = 1; i <= panSteps; i++) {
          let elapsed = this.pan.duration * (i / panSteps);
          let newLat = this.easeOutQuad(elapsed, curLat, dLat, this.pan.duration);
          let newLng = this.easeOutQuad(elapsed, curLng, dLng, this.pan.duration);
          panPath.push({ lat: newLat, lng: newLng })
        }
        panPath.push(position)
        panPath.shift() // LAZY SYNCRONIZED LOCK
        
        this.timeout = setTimeout(this.doPan, this.pan.duration / this.pan.steps)
      }
    },

    doPan () {
      var next = this.pan.path.shift();
        
      if (next != null) {
        // Continue our current pan action
        this.mapCenter = next;
        this.timeout = setTimeout(this.doPan, this.pan.duration / this.pan.steps);
      } else {
        // We are finished with this pan - check if there are any queue'd up locations to pan to 
        var queued = this.pan.queue.shift();
        if (queued != null) {
          this.panTo(queued);
        } else {
          clearTimeout(this.timeout);
        }
      }
    },
    
    updateCenter (ev) {
      let newLat = ev.lat();
      let newLng = ev.lng();
      if (this.mapCenter.lat !== newLat || this.mapCenter.lng !== newLng) {
        this.mapCenter = { lng: newLng, lat: newLat }
      }
    },
    
    // https://github.com/danro/jquery-easing/blob/master/jquery.easing.js
    // t: current time, b: beginning value, c: change in value, d: duration
    easeOutQuad: function (t, b, c, d) {
      return -c * (t /= d) * (t - 2) + b;
    }
  }
}
</script>

<style>

.infoWindow {
  text-align: center;
}
.infoWindow h1 {
  font-size: 20px;
  font-weight: bold;
}

.column { display: flex; flex-flow: column nowrap; align-items: stretch;}

.column .row { flex: 1; }
.column .row, .column .row-auto { width: 100%; }

.map {
  width: 100%; 
  height: 100%; 
}
</style>