name: clean artifacts

on:
  schedule:
    - cron: '0 1 * * *'
  
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        uses: glassechidna/artifact-cleaner@master
        with:
          minimumAge: 432000 # all artifacts at least 5 days old