name: Graaly Build Test & Build
on:
  push:
    branches:
      - master
      - dev
      - tests
      - check-network-quality
      - lambda
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: 'ubuntu-latest'
    # please disable this for prod use :
    continue-on-error: true
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      # use this later  
      # - name: Start MongoDB
      #   uses: supercharge/mongodb-github-action@1.3.0
      #   with:
      #     mongodb-version: 4.2.8

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run : npm ci

      - name: Lint
        run : npm run lint
        continue-on-error: true

      - name: Test
        run : node --experimental-modules test/index.mjs
        continue-on-error: true
      
      - name: Cypress test
        run : npm run test:e2e:CI
        continue-on-error: true

  build_pwa:
    needs: test
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [10.x]
    continue-on-error: true

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Quasar & Cordova
        run : npm install -g @quasar/cli cordova

      - name: npm install
        run : npm ci

      - name: quasar info
        run : quasar info

      - name: build pwa
        run : quasar build -m pwa

      - name: Artifact creation
        uses: actions/upload-artifact@v1
        with:
          name: Build Artifact
          path: dist/

  build_android:
    needs: test
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [10.x]
    continue-on-error: true
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Quasar & Cordova
        run : npm install -g @quasar/cli cordova

      - name: npm install
        run : npm ci

      - name: quasar info
        run : quasar info

      - name : Set up android sdk
        run: sudo apt install android-sdk

      - name: build android
        run : echo "test"
      #run : quasar build -m cordova -T android

      - name: Artifact creation
        uses: actions/upload-artifact@v1
        with:
          name: Build Artifact
          path: dist/
  
  build_ios:
    needs: test
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [10.x]
    continue-on-error: true
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Quasar & Cordova
        run : npm install -g @quasar/cli cordova

      - name: npm install
        run : npm ci

      - name: quasar info
        run : quasar info

      - name: build ios
        run : echo "test"
      #   run : quasar build -m cordova -T ios

      - name: Artifact creation
        uses: actions/upload-artifact@v1
        with:
          name: Build Artifact
          path: dist/